name: Update Discussions
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false   # do not use the default GITHUB_TOKEN

      - name: Run fetch script
        run: node fetch-discussions.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # same PAT you added

      - name: Commit and push changes with PAT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes" || git commit -m "Update discussions"
          git push https://x-access-token:${GH_TOKEN}@github.com/Aqib121201/Reproducible-AI-Systems.git HEAD:main
